### ISSUE TITLE
Hardcoded: IQ increasing items

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple-files#127]
The table that determines IQ gained by eating gummies can be found at [EU]arm9.bin:0xA2834 / [US]arm9.bin:0xA22B0
It has the same format as the type effectiveness table (18x18 entries, 2 bytes each)
For wonder gummies: EU: 0xa1e14 (US: arm9.bin:0xA1890)
EU: The IQ that a wonder gummi gives is inside arm9.bin:0xa1e14

where is Nectar IQ value fixed?:
[EU]overlay_0029.bin:0x40264 / [US]overlay_0029.bin:0x40144
The default value should be 10

Juice Bar Nectar:
[EU]arm9.bin:0x118B8 / [US]arm9.bin:0x11810

**Comment by irdkwia** [comment]
Be careful because the AddFairyType patch modifies the IQ gain table (same location 25x25 entries, 1 byte each) to add some space for the new type.
Same thing for the Gummi Belly Heal Table that determines how much belly points they heal depending on the type (at arm9.bin:0xA2538 [US], arm9.bin:0xA2ABC [EU], same format)
