### ISSUE TITLE
Harcoded: Dungeon guest Pokémon

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#28]
See dungeon document

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#skytemple-tester`.

**Comment by Parakoopa** [comment]
@End45 Do you think we could find a good way to also make the dungeon IDs assignable to the entries in SkyTemple?

**Comment by End45** [comment]
I've been looking into this, it might be possible to make a patch that replaces all the hardcoded ID checks with a table that maps dungeon IDs to additional pokémon entries which could then be edited with SkyTemple. This would also allow adding or removing entries, since removing the original code frees some space.
It would require some time to implement it though. Once my holidays start I could look into it.

**Comment by End45** [comment]
Done in https://github.com/SkyTemple/skytemple/pull/310
@Parakoopa This should be closed now
